### ISSUE TITLE
Composing Handlers?

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/bottender#342] opened 2018-10-01 04:27 UTC
Hello,
Is Is possible to using multiple levels of handler?
for exmpale:

```js
bot.onEvent(mainHandler)
const mainHandler = new LineHandler()
    .onFollow(async context => {
        return true
    }, followHandler)
    .onUnfollow(async context => {
        return true
    }, unfollowHandler)
    .onEvent(middleware([
        termAndServiceAgreement,
        isLoggedIn,
        eventHandlers
    ]))
    .onError(async (context, err) => {
        await context.sendText(err)
    })
    .onUnhandled(doNothing)

const eventHandlers = new LineHandler()
    .onEvent(async context => {
        const answer = 'somthing';
        switch (answer) {
            case case1:
                context([]);
                break;
            case case2:
                const anotherHandler = handler1.build()
                anotherHandler(context)
                break;
            default:
                // code
                doNothing()
        }
    })

const handler1 = new LineHandler()
    .onEvent(async context => {
        // do something
    })
```

I see there bottender-compose, but it seems i can't do something in the second parameter, only send actions.

```js
bot.onEvent(
  condition([
    [context => false, sendText('a')],
    [context => false, sendText('b')],
    [context => true, sendText('c')],
  ])
);
```

what if i i wanna check something in context.state and call 3r party services or pass to another event handler??

Thanks~~~

**Comment by tw0517tw** [comment] 2018-10-01 07:32
It's possible to compose multiple handlers. 

For handler builder, you can do
```js
const handlerA = new LineHandler().onEvent(context => context.sendText('A'));
const handlerB = new LineHandler().onEvent(context => context.sendText('B'));

const composedHandler = new LineHandler().onText('A', handlerA).onText('B', handlerB);

bot.onEvent(composedHandler);
```

For `bottender-compose`, 
```js
const handler = series([
  random([
    sendText('A'),
    sendText('B'),
  ]),
  branch(
    context => true,
    sendText('You are the lucky one.'),
    sendText('Too bad.')
  )
])

bot.onEvent(handler);
```

You can even mix the use of both ways.

**Comment by yusef-ho** [comment] 2018-10-02 01:15
@tw0517tw 
Thanks, can i use bottender-compose and pass context to second parameter of random/branch? or only actions on the list?

**Comment by tw0517tw** [comment] 2018-10-02 02:18
Hi @yusef-ho 

Sure, all the `bottender-compose` actions are only functions that accept `context` as first parameter.

```js
const handler = series(
  [
    sendText('Please wait'),
    async context => {
      const data = await callAPI(context.event.text);
      await context.sendText(data);
    },
  ]
)
```

**Comment by tw0517tw** [comment] 2018-10-03 12:35
Hi @yusef-ho ,

`doNothing()` will not mark the current `context` as handled, so the `onEvent()` callback will still be triggered, that's by design.
If you want to build a more complicate business logic, you can just skip the Hndler Builder classes and build your own logic. For example, you can set up a 
```
event + state -> action + next state
```
transform and put your business logic in it. Feel free to compose handlers in your way, they are just functions accept `context` as argument.

**Comment by yusef-ho** [comment] 2018-10-06 12:55
@tw0517tw 
Thank you~~~
i don't really get the idea `event + state -> action + next state`
Can you explain more Please
Thanks

**Comment by yusef-ho** [comment] 2018-10-09 16:03
@tw0517tw 
Thanks. currently everything works well with the following
```
bot.onEvent(mainHandler)
```
```javascript
// mainHandler
module.exports = new LineHandler()
    .onFollow(async context => {
        return true
    }, followHandler)
    .onUnfollow(async context => {
        return true
    }, unfollowHandler)
    .onEvent(condition([
        [context => {
            // Can i do something async function/promise to check with 3rd party service here??
            return true
        }, async context => {
            await context.sendText('need to logged in');
        }],
        [context => {
            // if user agree terms of service
        }, sendText('b')],
        [context => true, businessLogicHandler],
    ]))
    .onError(async (context, err) => {
        const msg = `不好意思，目前服務暫時出了點問題呢! 請稍待片刻再重試唷~`
        console.error(err);
        await context.sendText(msg)
    })
```

But it seems if i and doing something async in condition first arg, i always got "TypeError: action is not a function", I would like to know can i perform async operation there? or it just keeping pass to next tick?

Thank you~~

**Comment by yusef-ho** [comment] 2018-11-27 06:55
@tw0517tw Thanks for the reply.

Currently there's a weird behavior happening.
with normal text message unhandled, it will only be triggered once. but with postback message, it will be triggered twice.
i have the following code.
```javascript
// index.js
bot(mainHandler)
```
```javascript
// mainHandler
module.exports = new LineHandler()
    .onFollow(async context => {
        // handle follow event
        return true
    }, followHandler)
    .onUnfollow(async context => {
        return true
    }, unfollowHandler)
    .onEvent(condition([
        // Condition 1: check if user is LoggedIn
        [async context => {
            // some condition
            return false
        }, async context => {
            // some reply
        }],
        
        // Condition 2: User need to agree terms of service
        [async context => {
            // some condition
        }, async context => {
            context.reply([
                require('./reusableMessages/termsOfService').agreement
            ])
        }],

        // Condition 3: everything passed
        [context => true, servicesHandler],
    ]))
    .onError(async (context, err) => {
        const msg = `不好意思，目前服務暫時出了點問題呢! 請稍待片刻再重試唷~`
        console.error(err);
        await context.sendText(msg)
    })
    .onUnhandled(async context => {
        if (context.event.isUnfollow) doNothing()
        else {
            // TODO: modify the link to our real link connecting to us
            const customerServiceAccountLink = 'https://line.me/R/ti/p/%40ggn0079p'
            const msg = `您好，目前我無法了解您的意思，若有任何問題請洽詢客服，點擊以下網址加入客服 LINE @${customerServiceAccountLink}`
            await context.sendText(msg)   
        }
    })
    .build()
```
```javascript
// servicesHandler
const serviceRouter = new LineHandler()
    .onEvent(async context => {
        // check current service in state
        switch (context.state.service) {
            case 'Q&A':
                await QAServiceHandler(context)
                break;

            case 'one':
                await serviceOne(context)
                break;
        }
    })
    .build()

module.exports = new LineHandler()
    .onText(/\/menu/, async context => {
        context.resetState();
        await context.reply([
            require('../reusableMessages/servicesMenu')
        ])
    })
    .onText(/\/Q&A/, async context => {
        context.setState({
            service: 'Q&A'
        })
        await serviceRouter(context);
    })
    .onText('/one', async context => {
        context.resetState()
        context.setState({
            service: 'one'
        })
        await serviceRouter(context)
    })
    .onEvent(async context => {
        if (context.state.service) {
            await serviceRouter(context);
        } else {
            console.error('No service specified in state');
        }
    })
    .onError(async (context, err) => {
        console.log(err);
        await context.push([
            Line.createText(`小幫手目前無法為您服務，請您稍待重試。`)
        ])
    })
    .onUnhandled(async context => {
        await context.reply([
            Line.createText('小幫手不了解您目前想操作的服務，請重新選擇一項服務'),
            require('../reusableMessages/servicesMenu')
        ])
    })
    .build()
```
```javascript
// serviceOneHandler
module.exports = new LineHandler()
    .onEvent(questionsHandler)
    .onError(async (context, err) => {
        console.error(err);
        await context.sendText(`不好意思，目前小幫手出了點狀況呢！無法幫你處理自助列印的服務`)
    })
    .onUnhandled(async context => {
        await context.push([
            Line.createText('不好意思，目前無法處理您自助列印的服務需求'),
            require('../../reusableMessages/servicesMenu')
        ])
        // TODO: send lastest messages again
    })
    .build()
```
```javascript
// questionsHandler
const handler = require('./handler');
module.exports = new LineHandler()
    .onEvent(condition([
        [context => false, sendText('b')],
        [context => {
            debug('default action')
           // I understand i need to return true here
        }, sendText('c')],
    ]))
    .onError(async (context, err) => {
        console.error(err);
        await context.sendText(`不好意思，目前小幫手出了點狀況呢！無法幫你處理自助列印的服務`)
    })
    .onUnhandled(async context => {
        debug('unhandled in questionsHandler')
        await context.push([
            Line.createText('unhandled in questionsHandler'),
            Line.createText('不好意思，目前無法處理您自助列印的服務需求'),
            require('../../../reusableMessages/servicesMenu')
        ])
        // TODO: send lastest messages again
    })
    .build()
```

and i did some test in another LineHandler().build()
event i already deal with postback, but it still triggered onUnhandled
```javascript```
module.exports = new LineHandler()
    .onPostback(postback => {        
        const postbackData = postback.data        
        if (postbackData === 'yes' || postbackData === 'no') {
            return true
        }
        return false
    }, async context => {
        const postbackData = context.event.postback.data;
        if (postbackData === 'yes') {
            // if only one page for the document
            if (somecondtion = 'condition') {
                context.setState({
                    something: 'something'
                })
            }
            await require('anotherHandler')(context)
        } else if (postbackData === 'no') {
            await context.reply([
                Line.createText('TODO: Redirect User to Q & A')
            ])
        }
    })
    .onError(async (context, err) => {
        console.error(err);
        await context.push([
            Line.createText(`不好意思，小幫手在處理收到您的文件的過程中，出了點問題呢！無法幫你處理自助列印的服務，請稍後再試！`)
        ])
    })
    .onUnhandled(async context => {
        console.log('unhandled');
        // TODO: send lastest messages again
    })
    .build()
```

**Comment by tw0517tw** [comment] 2018-11-27 08:38
Hi @yusef-ho ,

You can try use `DEBUG` environment varaible to check incoming events, then you may find out what events are triggering what actions.

https://bottender.js.org/docs/Guides-Troubleshooting#i-want-to-know-if-therere-incoming-requests-to-my-bot

**Comment by yusef-ho** [comment] 2018-11-27 09:44
@tw0517tw 
Thanks. I realized where the issue happened. When the attribute in of action is text instead of displayText in postback, Line send two events, one is text message, another is postback.

**Comment by tw0517tw** [comment] 2018-11-30 08:57
I'm going to close this issue.

**Closed by tw0517tw** 2018-11-30 08:57 UTC
Labels: question
